export const ARCANE_RIVER_AREA_DATA = [
  {
    left: 6,
    top: 5,
    dotLeft: 94,
    dotTop: 88,
    name: "vanishing_journey",
  },
  {
    left: 170,
    top: 14,
    dotLeft: 56,
    dotTop: 33,
    name: "reverse_city",
  },
  {
    left: 34,
    top: 254,
    dotLeft: 91,
    dotTop: 52,
    name: "chu_chu_island",
  },
  {
    left: 25,
    top: 355,
    dotLeft: 39,
    dotTop: 24,
    name: "yum_yum_island",
  },
  {
    left: 100,
    top: 122,
    dotLeft: 91,
    dotTop: 76,
    name: "lachelein",
  },
  {
    left: 255,
    top: 71,
    dotLeft: 81,
    dotTop: 61,
    name: "arcana",
  },
  {
    left: 238,
    top: 223,
    dotLeft: 81,
    dotTop: 97,
    name: "morass",
  },
  {
    left: 388,
    top: 168,
    dotLeft: 104,
    dotTop: 75,
    name: "esfera",
  },
  {
    left: 387,
    top: 280,
    dotLeft: 86,
    dotTop: 43,
    name: "sellas",
  },
  {
    left: 406,
    top: 20,
    dotLeft: 87,
    dotTop: 70,
    name: "tenebris",
  },
  {
    left: 0,
    top: 6,
    dotLeft: 127,
    dotTop: 173,
    name: "moonbridge",
    parentArea: "tenebris",
  },
  {
    left: 210,
    top: 0,
    dotLeft: 112,
    dotTop: 205,
    name: "labyrinth_of_suffering",
    parentArea: "tenebris",
  },
  {
    left: 333,
    top: 0,
    dotLeft: 120,
    dotTop: 120,
    name: "limina",
    parentArea: "tenebris",
  },
];

export const GRANDIS_AREA_DATA = [
  {
    left: 87,
    top: 205,
    dotLeft: 80,
    dotTop: 24,
    name: "cernium",
  },
  {
    left: 529,
    top: 19,
    dotLeft: 0,
    dotTop: 0,
    name: "cernium2",
    parentArea: "burning_cernium",
  },
  {
    left: 525,
    top: 14,
    dotLeft: 0,
    dotTop: 0,
    name: "burning_cernium",
    parentArea: "cernium",
  },
  {
    left: 191,
    top: 189,
    dotLeft: 58,
    dotTop: 34,
    name: "hotel_arcus",
  },
  {
    left: 282,
    top: 103,
    dotLeft: 43,
    dotTop: 48,
    name: "odium",
  },
  {
    left: 419,
    top: 14,
    dotLeft: 0,
    dotTop: 0,
    name: "odium2",
    parentArea: "shangri_la",
  },
  {
    left: 485,
    top: 22,
    dotLeft: 0,
    dotTop: 0,
    name: "shangri_la",
    parentArea: "odium",
  },
  {
    left: 51,
    top: 109,
    dotLeft: 54,
    dotTop: 44,
    name: "arteria",
  },
  {
    left: 83,
    top: 317,
    dotLeft: 51,
    dotTop: 57,
    name: "carcion",
  },
];

export const AREAS_WITH_PARENT_AREAS = {
  moonbridge: "tenebris",
  labyrinth_of_suffering: "tenebris",
  limina: "tenebris",
  burning_cernium: "cernium",
  shangri_la: "odium",
};
